/** User-facing copy for the Next.js shell — single source of truth. */

export const SHELL_COPY = {
  brand: {
    name: 'NEON NEXUS',
    nameLine1: 'NEON',
    nameLine2: 'NEXUS',
    tagline: 'Bullet-Time Brickbreaker · Twilight Garden Siege',
    taglineShort: 'Bullet-Time Brickbreaker',
  },
  home: {
    chapter: 'TWILIGHT GARDEN SIEGE',
    menuLabel: 'MAIN MENU',
    stats: (highScore: number, gems: number) =>
      `Personal best ${highScore.toLocaleString()} · ${gems.toLocaleString()} gems`,
    savedRun: (level: number, score: number, lives: number) =>
      `Continue — Level ${level} · ${score.toLocaleString()} pts · ${lives} ${lives === 1 ? 'life' : 'lives'}`,
    installAccepted: 'Installed. Welcome to the garden.',
    installManual: 'Use your browser menu: Add to Home Screen or Install app.',
    nav: {
      play: 'START GAME',
      resume: 'CONTINUE',
      newGame: 'NEW GAME',
      codex: 'CODEX',
      shop: 'GARDEN SHOP',
      settings: 'SETTINGS',
      share: 'SHARE PROGRESS',
      shareShort: 'SHARE',
      install: 'INSTALL APP',
      installShort: 'INSTALL',
      connect: 'CONNECT',
      connectShort: 'CONNECT',
    },
  },
  settings: {
    title: 'SETTINGS',
    vfxLabel: 'GRAPHICS',
    soundFx: 'SOUND EFFECTS',
    music: 'MUSIC',
    sfxVolume: 'SFX VOLUME',
    musicVolume: 'MUSIC VOLUME',
    adsRemoved: 'Ad-free experience active. Thank you for your support.',
    removeAds: (price: string) => `REMOVE ADS — ${price}`,
    restore: 'RESTORE PURCHASES',
    redeem: 'REDEEM UNLOCK CODE',
    shopLink: 'OPEN GARDEN SHOP',
    status: {
      checkout: 'Opening secure checkout…',
      adsRemoved: 'Ads removed. Thank you!',
      restoring: 'Restoring purchases…',
      restored: 'Purchases restored.',
      noPurchases: 'No previous purchases found for this account.',
      redeemPrompt: 'Enter your unlock code when prompted.',
      unlocked: 'Content unlocked.',
    },
  },
  shop: {
    title: 'GARDEN SHOP',
    subtitle: 'Unlock cosmetics with gems earned in battle. Equip to see changes in your next run.',
    balance: (gems: number) => `${gems.toLocaleString()} gems available`,
    equipped: (hull: string, trail: string, theme: string) =>
      `Equipped — ${hull} hull · ${trail} trail · ${theme} garden`,
    supportTitle: 'SUPPORT THE STUDIO',
    gemPack: 'GEM PACK',
    premium: 'PREMIUM PASS',
    status: {
      equippedLive: 'Equipped. Return to your run to see it in the arena.',
      equipped: 'Equipped.',
      equipFailed: 'Could not equip that item.',
      premiumRequired: 'Requires Premium Pass — see Support below.',
      premiumSoon: 'Premium cosmetics arrive in a future update.',
      unlocked: 'Unlocked and equipped.',
      insufficientGems: 'Not enough gems — clear more bricks or visit Support.',
      processing: 'Processing purchase…',
      thanks: 'Thank you. Enjoy the garden.',
    },
    actions: {
      equip: 'EQUIP',
      active: 'ACTIVE',
      premium: 'PREMIUM',
      free: 'FREE',
      gems: (n: number) => `${n} 💎`,
    },
  },
  codex: {
    tabs: {
      guide: 'GUIDE',
      powers: 'POWERS',
      bestiary: 'BESTIARY',
      journal: 'JOURNAL',
    },
    journalEmpty: 'Keep playing to unlock journal milestones.',
    stats: {
      games: 'Sessions played',
      bricks: 'Bricks destroyed',
      gnomes: 'Jardinains defeated',
      combo: 'Highest combo multiplier',
    },
  },
  share: {
    title: 'SHARE',
    preparing: 'Forging your siege card…',
    retry: 'SHARE AGAIN',
    status: {
      preparing: 'Opening share sheet…',
      shared: 'Shared — thanks for spreading the word.',
      saved: 'Card saved to your device.',
      savedClipboard: 'Card saved. Caption copied to clipboard.',
      cancelled: 'Share cancelled.',
      failed: 'Could not share — try again.',
    },
  },
  install: {
    title: 'INSTALL APP',
    subtitle: 'Add Neon Nexus to your home screen for quick access.',
    installed: 'You are running the installed app. Thanks for playing.',
    body: 'Install for a home-screen shortcut, faster launch, and the same progress when you return online.',
    cta: 'INSTALL NOW',
    manualIos: 'On iPhone or iPad: Share, then Add to Home Screen.',
    manualAndroid: 'On Android or desktop Chrome: open the menu, then Install app.',
    status: {
      accepted: 'Installed. See you in the garden.',
      unavailable: 'Install is not available here. Use your browser’s Add to Home Screen option.',
      dismissed: 'Install dismissed. You can try again anytime.',
    },
    playProtectTitle: 'Seeing “Unsafe app blocked” on Android?',
    playProtectBody:
      'That warning is from Google Play Protect, not the game. It often appears when an older Neon Nexus APK is on the phone, or when Chrome’s install check is strict. Uninstall any old “Neon Nexus” app in Settings → Apps, update Chrome, then install again from the browser—or keep playing at nnbr.netlify.app without installing.',
    playProtectPlayStore:
      'If you installed from a test APK or Play Store build, upload a new release built with target API 35 (pnpm run ship:android after cap:add:android).',
  },
  connect: {
    title: 'CONNECT',
    subtitle: 'Creator · Game developer',
    body: 'Neon Nexus is designed and built by Tuhin Karmakar. Reach out on LinkedIn for feedback, collaboration, or to share how far your siege has gone.',
    cta: 'MESSAGE ON LINKEDIN',
  },
  notFound: {
    title: 'PAGE NOT FOUND',
    subtitle: 'This path is not part of the garden. Head back to the hub to continue.',
    cta: 'RETURN HOME',
  },
  loading: {
    title: 'NEON NEXUS',
    subtitle: 'Opening the twilight garden…',
  },
  play: {
    bootTitle: 'NEON NEXUS',
    bootTagline: 'Bullet-Time Brickbreaker',
    bootSubtitle: 'Twilight Garden Siege',
    phases: {
      bundle: 'Loading siege engine…',
      engine: 'Initializing bullet-time…',
      textures: 'Forging bricks & Jardinains…',
      audio: 'Tuning garden audio…',
      garden: 'Planting the arena…',
      siege: 'Arming your siege…',
      ready: 'Garden ready — launch when you are',
      stuck: 'Still loading — almost there…',
    },
  },
  legal: {
    footerCredit: 'Made with care by Tuhin Karmakar',
  },
} as const;
