/** User-facing copy for the Next.js shell — single source of truth. */

export const SHELL_COPY = {
  brand: {
    name: 'NEON NEXUS',
    nameLine1: 'NEON',
    nameLine2: 'NEXUS',
    tagline: 'Bullet-Time Brickbreaker · Twilight Garden Siege',
    taglineShort: 'Bullet-Time Brickbreaker',
  },
  home: {
    chapter: 'TWILIGHT GARDEN SIEGE',
    menuLabel: 'MAIN MENU',
    stats: (highScore: number, gems: number) =>
      `Personal best ${highScore.toLocaleString()} · ${gems.toLocaleString()} gems`,
    savedRun: (level: number, score: number, lives: number) =>
      `Continue — Level ${level} · ${score.toLocaleString()} pts · ${lives} ${lives === 1 ? 'life' : 'lives'}`,
    installAccepted: 'Installed. Welcome to the garden.',
    installManual: 'Use your browser menu: Add to Home Screen or Install app.',
    nav: {
      play: 'START GAME',
      resume: 'CONTINUE',
      newGame: 'NEW GAME',
      codex: 'CODEX',
      shop: 'GARDEN SHOP',
      settings: 'SETTINGS',
      share: 'SHOW YOUR GARDEN',
      shareShort: 'GARDEN',
      install: 'INSTALL APP',
      installShort: 'INSTALL',
      connect: 'CONNECT',
      connectShort: 'CONNECT',
      tutorial: 'HOW TO PLAY',
    },
  },
  settings: {
    title: 'Settings',
    subtitle: '',
    sections: {
      account: 'Account & cloud sync',
      backup: 'Save backup',
      graphics: 'Graphics',
      audio: 'Audio',
      feedback: 'Feedback',
      purchases: 'Purchases',
      links: 'More',
    },
    vfxLabel: 'Graphics quality',
    soundFx: 'Sound effects',
    music: 'Music',
    ambience: 'Garden ambience',
    sfxVolume: 'SFX volume',
    musicVolume: 'Music volume',
    haptics: 'Haptic feedback',
    adsRemoved: 'Ad-free experience active. Thank you for your support.',
    removeAds: (price: string) => `REMOVE ADS — ${price}`,
    restore: 'RESTORE PURCHASES',
    redeem: 'REDEEM UNLOCK CODE',
    shopLink: 'OPEN GARDEN SHOP',
    codexLink: 'OPEN CODEX',
    status: {
      checkout: 'Opening secure checkout…',
      adsRemoved: 'Ads removed. Thank you!',
      restoring: 'Restoring purchases…',
      restored: 'Purchases restored.',
      noPurchases: 'No previous purchases found for this account.',
      redeemPrompt: 'Enter your unlock code when prompted.',
      unlocked: 'Content unlocked.',
    },
  },
  account: {
    title: 'Cloud sync',
    guestHint: 'Your progress is saved on this device only. Sign in with Google to sync across devices.',
    enableCloudSync: 'Enable cloud sync',
    signedInAs: (email: string) => `Signed in as ${email}`,
    lastSynced: (when: string) => `Last synced ${when}`,
    syncPending: 'Sync pending…',
    syncNow: 'Sync now',
    signOut: 'Sign out',
    loading: 'Checking account…',
    notConfigured:
      'Your progress is saved on this device automatically. Cloud sign-in is not available in this build — use Export / Import below to back up manually.',
    notConfiguredDev:
      'Cloud sign-in is off until Firebase env vars are set (see docs/CLOUD_SAVE.md). Players will see an “Enable cloud sync” button once deployed.',
    exportSave: 'Export save file',
    importSave: 'Import save file',
    deleteAccount: 'Delete account & cloud save',
    nudge: {
      title: 'Save your garden to the cloud',
      body: 'Your progress is stored on this device only. Sign in with Google to sync across devices and never lose your gems.',
      enable: 'Enable cloud sync',
      dismiss: 'Not now',
    },
  },
  shop: {
    title: 'Garden Shop',
    subtitle: 'Unlock cosmetics with gems earned in battle. Equip to see changes in your next run.',
    balance: (gems: number) => `${gems.toLocaleString()} gems available`,
    equipped: (hull: string, trail: string, theme: string) =>
      `Equipped — ${hull} hull · ${trail} trail · ${theme} garden`,
    supportTitle: 'SUPPORT THE STUDIO',
    gemPack: 'GEM PACK',
    premium: 'PREMIUM PASS',
    status: {
      equippedLive: 'Equipped. Return to your run to see it in the arena.',
      equipped: 'Equipped.',
      equipFailed: 'Could not equip that item.',
      premiumRequired: 'Requires Premium Pass — see Support below.',
      premiumSoon: 'Premium cosmetics arrive in a future update.',
      unlocked: 'Unlocked and equipped.',
      insufficientGems: 'Not enough gems — clear more bricks or visit Support.',
      processing: 'Processing purchase…',
      thanks: 'Thank you. Enjoy the garden.',
    },
    actions: {
      equip: 'EQUIP',
      active: 'Equipped',
      equipped: 'Equipped',
      premium: 'PREMIUM',
      free: 'FREE',
      gems: (n: number) => `${n} 💎`,
    },
    confirm: {
      title: 'Spend gems?',
      body: (label: string, cost: number) => `Unlock ${label} for ${cost.toLocaleString()} gems?`,
      balance: (before: number, after: number) =>
        `${before.toLocaleString()} gems → ${after.toLocaleString()} after purchase`,
      balanceInsufficient: (balance: number, cost: number) =>
        `You have ${balance.toLocaleString()} gems · costs ${cost.toLocaleString()}`,
      insufficient: (shortfall: number) =>
        `Not enough gems — you need ${shortfall.toLocaleString()} more to purchase.`,
      previewLabel: 'Equipped preview',
      confirm: 'Confirm purchase',
      confirmDisabled: 'Not enough gems',
      cancel: 'Cancel',
    },
  },
  codex: {
    tabs: {
      guide: 'Guide',
      powers: 'Powers',
      bestiary: 'Bestiary',
      journal: 'Journal',
    },
    journalEmpty: 'Keep playing to unlock journal milestones.',
    stats: {
      games: 'Sessions played',
      bricks: 'Bricks destroyed',
      gnomes: 'Jardinains defeated',
      combo: 'Highest combo multiplier',
    },
  },
  share: {
    title: 'Show your garden',
    subtitle: 'Preview your twilight garden card, then share',
    preparing: 'Growing your garden card…',
    previewHint: 'Your garden card — tap Share when ready',
    shareCta: 'SHOW YOUR GARDEN',
    retry: 'SHARE AGAIN',
    status: {
      preparing: 'Opening share sheet…',
      shared: 'Shared — thanks for spreading the word.',
      saved: 'Card saved to your device.',
      savedClipboard: 'Card saved. Caption copied to clipboard.',
      cancelled: 'Share cancelled.',
      failed: 'Could not share — try again.',
    },
  },
  install: {
    title: 'Install app',
    subtitle: 'Add Neon Nexus to your home screen for quick access.',
    installed: 'You are running the installed app. Thanks for playing.',
    body: 'Install for a home-screen shortcut, faster launch, and the same progress when you return online.',
    cta: 'INSTALL NOW',
    manualIos: 'On iPhone or iPad: Share, then Add to Home Screen.',
    manualAndroid: 'On Android or desktop Chrome: open the menu, then Install app.',
    status: {
      accepted: 'Installed. See you in the garden.',
      unavailable: 'Install is not available here. Use your browser’s Add to Home Screen option.',
      dismissed: 'Install dismissed. You can try again anytime.',
    },
    playProtectTitle: 'Seeing “Unsafe app blocked” on Android?',
    playProtectBody:
      'That warning is from Google Play Protect, not the game. It often appears when an older Neon Nexus APK is on the phone, or when Chrome’s install check is strict. Uninstall any old “Neon Nexus” app in Settings → Apps, update Chrome, then install again from the browser—or keep playing at nnbr.netlify.app without installing.',
    playProtectPlayStore:
      'If you installed from a test APK or Play Store build, upload a new release built with target API 35 (pnpm run ship:android after cap:add:android).',
  },
  connect: {
    title: 'Connect',
    subtitle: 'Creator · Game developer',
    body: 'Neon Nexus is designed and built by Tuhin Karmakar. Reach out on LinkedIn for feedback, collaboration, or to share how far your siege has gone.',
    externalHint: 'Opens LinkedIn in a new tab — you can return here with your browser back button.',
    cta: 'Message on LinkedIn',
  },
  notFound: {
    title: 'Page not found',
    subtitle: 'This path is not part of the garden. Return to the hub to continue.',
    cta: 'RETURN HOME',
  },
  loading: {
    title: 'NEON NEXUS',
    subtitle: 'Opening the twilight garden…',
  },
  play: {
    bootTitle: 'NEON NEXUS',
    bootTagline: 'Bullet-Time Brickbreaker',
    bootSubtitle: 'Twilight Garden Siege',
    phases: {
      bundle: 'Loading siege engine…',
      engine: 'Initializing bullet-time…',
      textures: 'Forging bricks & Jardinains…',
      audio: 'Tuning garden audio…',
      garden: 'Planting the arena…',
      siege: 'Arming your siege…',
      ready: 'Garden ready — launch when you are',
      stuck: 'Still loading — almost there…',
      stuckRetry: 'Taking longer than usual — tap to continue',
    },
    bootStuck: {
      retry: 'Continue anyway',
      refresh: 'Refresh page',
    },
    bootError: {
      title: 'Could not start the garden',
      detail: 'The siege engine failed to load. This is usually a network hiccup or an outdated cache.',
      hint: 'Check your connection, then try again. If this keeps happening, return to the hub and start a new run.',
      retry: 'Try again',
      home: 'Back to hub',
    },
  },
  legal: {
    footerCredit: 'Made with care by Tuhin Karmakar',
  },
} as const;
