/** Writes src/config/Version.js from package.json + git short hash (run on prebuild). */
import { execSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(fileURLToPath(import.meta.url));
const pkg = JSON.parse(readFileSync(resolve(root, '../package.json'), 'utf8'));
let stamp = 'dev';
try {
  stamp = execSync('git rev-parse --short HEAD', { cwd: resolve(root, '..'), encoding: 'utf8' }).trim();
} catch { /* not a git repo */ }

const out = resolve(root, '../src/config/Version.js');
writeFileSync(
  out,
  `/** Auto-generated by scripts/stamp-version.mjs — do not edit by hand. */\nexport const APP_VERSION = '${pkg.version}';\nexport const BUILD_STAMP = '${stamp}';\n`,
);
